### PR TITLE
PR#3 

### LINKED ISSUE #3: Genre matching
Store only those films in the .csv file whose genre matches with the genre user enters in the input, take input from user along with the input directory path (which is already taken).

### PR DESCRIPTION
**Pull request by sarthak55k**
Asking the user if he/she wants to filter the movies or not

### CODE REVIEW

**Comment by sarthak55k** [comment]
i think you have merged some other pull request thats which conflicts have been genrated

**Comment by utkarshbajaj** [comment]
Yes, please pull the latest changes and then submit the pull request again, I will merge it.

**Comment by sarthak55k** [comment]
Can you just merge my pull request

**Comment by sarthak55k** [comment]
closes #3

**Comment by utkarshbajaj** [comment]
Hey, I cannot merge it right now because this runs on a gui now. I'll get back to this, can you merge the genre asking part in the GUI?

**Comment by utkarshbajaj** [comment]
However, I have put this as Hacktoberfest accepted, I have created a new branch called genre specific, if you make a pull request to that branch ill merge it.

**Comment by sarthak55k** [comment]
currently working on some different project 
if got some time i will surely do it

**Pull request closed without merging**
