### PR TITLE
Added GUI script

### PR DESCRIPTION
**Pull request by Aravindha1234u**
Have a look into it. I have added GUI python script which works Perfectly.

for Issue #4

### CODE REVIEW

**Comment by utkarshbajaj** [comment]
Can you do changes in the Readme as well, also can you put up screenshot of the gui in readme

**Comment by utkarshbajaj** [comment]
Also this has one conflict, please git pull the latest changes also 
I'll merge then.

**Comment by Aravindha1234u** [comment]
@utkarshbajaj Can you check now Bro. I have resolved the conflict and added screenshots too.

**Comment by utkarshbajaj** [comment]
Great, Thanks a lot!

**Pull request merged**
