### PR TITLE
PR for issue #1

### LINKED ISSUE #1: Extract film name from directory even if it has _
If the film name is star_wars_episode_one.mp4 the url ending generated should be star+wars+episode+one, right now this works for spaces only. (Eg. Star Wars works but star_wars doesn't)

### PR DESCRIPTION
**Pull request by Vipul-Bajaj**
This pr fixes #1

### CODE REVIEW

**Comment by utkarshbajaj** [comment]
Did you run it?

**Comment by Vipul-Bajaj** [comment]
> Did you run it?

yes, tried with names like "the_little_rascals" and "the little_rascals", worked fine for both

**Comment by utkarshbajaj** [comment]
> > Did you run it?
> 
> yes, tried with names like "the_little_rascals" and "the little_rascals", worked fine for both

Great.

**Comment by utkarshbajaj** [comment]
You can delete this branch safely.

**Pull request merged**
